# Generated by Django 3.2.6 on 2021-08-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210803_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list',
            new_name='task_list',
        ),
    ]
