# Generated by Django 3.2.6 on 2021-08-04 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_alter_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='title',
            new_name='list_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
